#!/usr/bin/env python
# encoding: utf-8
"""
smallify.py

Takes the large and extensive fitting file and reduces it 
simple and smaller output.

Created by Jonathan Whitmore on 2013-09-13.
Copyright (c) 2013 . All rights reserved.
"""

import sys
import os
import dateutil
import glob
import cPickle as pickle
import gzip
import calicompari as calicompari


big_cal_file = sys.argv[1]

try: 
    prefix =  sys.argv[2]
except:
    prefix = "small_"
    
print "prefix is:", prefix
outfile = prefix + big_cal_file
print outfile

expo = calicompari.load_exposure(big_cal_file)

small_dictionary = {}

small_dictionary['Results'] = expo.Results
small_dictionary['arc_header'] = expo.arc_header
small_dictionary['flux_header'] = expo.flux_header
small_dictionary['header'] = expo.header
try:
    small_dictionary['exposure_file'] = expo.exposure_file
except:
    small_dictionary['exposure_file'] = expo.exposureFile
small_dictionary['safe_orders'] = expo.safe_orders

with gzip.open(outfile, 'wb') as file_handle:
    pickle.dump(small_dictionary, file_handle, pickle.HIGHEST_PROTOCOL)

